// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "products service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "List of products",
            "schema": {
              "$ref": "#/definitions/ProductsDto"
            }
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateProductDto"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Product created",
            "schema": {
              "$ref": "#/definitions/ProductDto"
            }
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get./products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Product",
            "schema": {
              "$ref": "#/definitions/ProductDto"
            }
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    }
  },
  "definitions": {
    "ProductDto": {
      "properties": {
        "id": {
          "title": "ProductDto.id",
          "type": "string"
        },
        "description": {
          "title": "ProductDto.description",
          "type": "string"
        },
        "price": {
          "title": "ProductDto.price",
          "type": "number"
        },
        "count": {
          "title": "ProductDto.count",
          "type": "number"
        }
      },
      "required": [
        "id",
        "price"
      ],
      "additionalProperties": false,
      "title": "ProductDto",
      "type": "object"
    },
    "CreateProductDto": {
      "properties": {
        "title": {
          "title": "CreateProductDto.title",
          "type": "string"
        },
        "description": {
          "title": "CreateProductDto.description",
          "type": "string"
        },
        "price": {
          "title": "CreateProductDto.price",
          "type": "number"
        },
        "count": {
          "title": "CreateProductDto.count",
          "type": "number"
        }
      },
      "required": [
        "title",
        "price"
      ],
      "additionalProperties": false,
      "title": "CreateProductDto",
      "type": "object"
    },
    "StockDto": {
      "properties": {
        "product_id": {
          "title": "StockDto.product_id",
          "type": "string"
        },
        "count": {
          "title": "StockDto.count",
          "type": "number"
        }
      },
      "required": [
        "product_id",
        "count"
      ],
      "additionalProperties": false,
      "title": "StockDto",
      "type": "object"
    },
    "ProductsDto": {
      "items": {
        "$ref": "#/definitions/ProductDto",
        "title": "ProductsDto.[]"
      },
      "title": "ProductsDto.[]",
      "type": "array"
    }
  },
  "securityDefinitions": {}
};