// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "import service",
    "version": "1"
  },
  "paths": {
    "/import": {
      "get": {
        "summary": "importProductsFile",
        "description": "",
        "operationId": "importProductsFile.get.import",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Signed url created",
            "schema": {
              "$ref": "#/definitions/ImportProductsDto"
            }
          },
          "400": {
            "description": "Bad request"
          }
        }
      }
    }
  },
  "definitions": {
    "ImportProductsDto": {
      "properties": {
        "url": {
          "title": "ImportProductsDto.url",
          "type": "string"
        }
      },
      "required": [
        "url"
      ],
      "additionalProperties": false,
      "title": "ImportProductsDto",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};